trigger:
  - master

pool:
  name: Default  # Make sure this pool is mapped to your WSL-based self-hosted agent

variables:
  imageName: 'flask-hello-world'

steps:
  - script: |
      echo "Checking Docker status..."
      docker version
      docker info
    displayName: 'Verify Docker Engine'
    shell: bash

  - script: |
      echo "Building Docker image..."
      docker build -t $(imageName) .
    displayName: 'Build Docker Image'
    shell: bash

  - script: |
      echo "Running Docker container locally (for test)..."
      docker run -d -p 5000:5000 $(imageName)
    displayName: 'Run Container Locally'
    shell: bash
