trigger:
- master

pool:
  name: Default  # Use your WSL self-hosted agent

variables:
  dockerHubUsername: 'balajibommidi4111@gmail.com'   # 👈 replace with your Docker Hub username
  imageName: 'flask-hello-app'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: 'latest'

- script: |
    docker build -t $(imageName) ./python-docker-demo
    docker tag $(imageName) $(dockerHubUsername)/$(imageName):latest
  displayName: 'Build and Tag Docker Image'

- script: |
    echo $(DOCKER_PASSWORD) | docker login -u $(dockerHubUsername) --password-stdin
    docker push $(dockerHubUsername)/$(imageName):latest
  displayName: 'Push Image to Docker Hub'
