trigger:
  - master

pool:
  name: Default  # Your self-hosted WSL agent

variables:
  imageName: 'flask-hello-world'

steps:
  - script: |
      echo "Checking Docker status..."
      docker version
      docker info
    displayName: 'Verify Docker Engine'

  - script: |
      echo "Building Docker image..."
      docker build -t $(imageName) .
    displayName: 'Build Docker Image'

  - script: |
      echo "Running Docker container locally (for test)..."
      docker run -d -p 5000:5000 $(imageName)
    displayName: 'Run Container Locally'
