trigger:
- master  # Change to 'main' if needed

pool:
  name: Default  # Use your WSL self-hosted agent pool name

variables:
  dockerHubUsername: 'balaji4111'   # ✅ Use Docker Hub username (not email)
  imageName: 'flask-hello-app'

steps:
- checkout: self  # ✅ Correct way to check out your repo in YAML

- script: |
    echo "Building and tagging Docker image..."
    docker build -t $(imageName) ./python-docker-demo
    docker tag $(imageName) $(dockerHubUsername)/$(imageName):latest
  displayName: 'Build and Tag Docker Image'

- script: |
    echo "Logging in to Docker Hub and pushing image..."
    echo $(DOCKER_PASSWORD) | docker login -u $(dockerHubUsername) --password-stdin
    docker push $(dockerHubUsername)/$(imageName):latest
  displayName: 'Push Image to Docker Hub'
