trigger:
- master  # You can change to 'main' if that's your branch

pool:
  name: Default  # Make sure this matches your self-hosted agent pool

variables:
  dockerHubUsername: 'balaji4111'   # ✅ Use your actual Docker Hub username (NOT email)
  imageName: 'flask-hello-app'

steps:
- task: Checkout@1

- script: |
    echo "Building and tagging Docker image..."
    docker build -t $(imageName) ./python-docker-demo
    docker tag $(imageName) $(dockerHubUsername)/$(imageName):latest
  displayName: 'Build and Tag Docker Image'

- script: |
    echo "Logging in to Docker Hub and pushing image..."
    echo $(DOCKER_PASSWORD) | docker login -u $(dockerHubUsername) --password-stdin
    docker push $(dockerHubUsername)/$(imageName):latest
  displayName: 'Push Image to Docker Hub'
